ARG FEDORA=43
FROM registry.fedoraproject.org/fedora:${FEDORA}
RUN dnf -y --setopt=install_weak_deps=False install gnome-shell gnome-extensions-app gjs libadwaita python3 dbus-daemon mesa-dri-drivers mesa-libEGL tzdata && dnf clean all
WORKDIR /work
